language: ruby
cache: bundler
rvm:
- 2.2
before_script:
- pip install --user -r requirements.txt
script:
- behave tests/before_build
- bundle exec jekyll build
- behave tests/after_build
deploy:
  - provider: pages
    skip_cleanup: false
    github_token: "$GITHUB_TOKEN"
    target_branch: gh-pages
    on:
      branch: master

  - provider: script
    script: chmod +x deploy/deploy.sh && deploy/deploy.sh
    skip_cleanup: true
    on:
      branch: master
addons:
  ssh_known_hosts: e2e.hasgeek.com
